version: 0.0
os: linux
files:
  - source: /cicd-aws.jar
    destination: /home/ubuntu/cicd-aws.jar
hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
