version: 0.0
os: linux
files:
  - source: target/*.jar
    destination: /home/ubuntu/springboot/
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
