version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - curl -sL https://apache.claz.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | tar xz -C /opt
      - export PATH=/opt/apache-maven-3.6.3/bin:$PATH
  pre_build:
    commands:
      - echo Pre-build started
      - mvn clean
  build:
    commands:
      - echo Building the project...
      - mvn install -DskipTests
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/cicd-aws.jar
